<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LOGER" />
    <InternalsVisibleTo Include="logReader.Tests" />
    <InternalsVisibleTo Include="logReader.UI.Tests" />
  </ItemGroup>

</Project>
